### PR TITLE
Some edits on new version of coding style

### PR DESCRIPTION
**Pull request by am0ka**
Now indentation is made by spaces, not tabulation. 1 identation = 4 spaces.

### CODE REVIEW

**Comment by selena81792** [comment]
Hi Amir I am Selena, thank you for making this, I am using your edit now, it is very useful for the pool, but the bot does not work for checking if the body of the function exceed 20 lines, do you have the same problem or it is just me?

**Comment by am0ka** [comment]
Hi Selena,
Yes, I will try to figure out this
*Cordialement**,*





*             http://www.epitech.eu/ <http://www.epitech.eu/>*

*Amir SARSENOV *

Etudiant 1ère année

Epitech. L'ecole de l'innovation
et de l'expertise informatique

Tel.: 06 24 54 48 00 <+33624544800>
24, rue Pasteur, 94270
Le Kremlin-Bicêtre, France


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality6&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality6&>
10/05/18,
6:36:40 PM

пт, 5 окт. 2018 г. в 18:33, selena81792 <notifications@github.com>:

**Comment by ronanboiteau** [comment]
Great! Thank you for the PR 👍

**Comment by am0ka** [comment]
What does the PR mean? Do you think, it is just because I want be in the
list of contributors?
No. I find your tool useful, so I think "why not to try?". Although, it is
my first experience with Ruby...😀
*Cordialement**,*





*             http://www.epitech.eu/ <http://www.epitech.eu/>*

*Amir SARSENOV *

Etudiant 1ère année

Epitech. L'ecole de l'innovation
et de l'expertise informatique

Tel.: 06 24 54 48 00 <+33624544800>
24, rue Pasteur, 94270
Le Kremlin-Bicêtre, France


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality6&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality6&>
10/05/18,
6:47:17 PM

пт, 5 окт. 2018 г. в 18:46, Ronan Boiteau <notifications@github.com>:

**Comment by ronanboiteau** [comment]
PR = Pull Request

**Comment by ronanboiteau** [comment]
No no, thanks for the update, really! 👌🏻

**Comment by am0ka** [comment]
Oh, sorry. I just thought about another thing in Marketing sphere
*Cordialement**,*





*             http://www.epitech.eu/ <http://www.epitech.eu/>*

*Amir SARSENOV *

Etudiant 1ère année

Epitech. L'ecole de l'innovation
et de l'expertise informatique

Tel.: 06 24 54 48 00 <+33624544800>
24, rue Pasteur, 94270
Le Kremlin-Bicêtre, France


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
10/05/18,
6:56:44 PM

пт, 5 окт. 2018 г. в 18:56, Ronan Boiteau <notifications@github.com>:

**Comment by ronanboiteau** [comment]
I just rolled out your update on the auto-update system. Feel free to open another pull request or an issue if something's buggy, I didn't test much!

**Comment by selena81792** [comment]
Ok thanks guys for the work, can I post my function where it failed to detect that it is bigger than 20 lines?

**Comment by am0ka** [comment]
Yes please! Because code seems to be okay.
*Cordialement**,*





*             http://www.epitech.eu/ <http://www.epitech.eu/>*

*Amir SARSENOV *

Etudiant 1ère année

Epitech. L'ecole de l'innovation
et de l'expertise informatique

Tel.: 06 24 54 48 00 <+33624544800>
24, rue Pasteur, 94270
Le Kremlin-Bicêtre, France


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
10/05/18,
7:00:59 PM

пт, 5 окт. 2018 г. в 19:00, selena81792 <notifications@github.com>:

**Comment by ronanboiteau** [comment]
@selena81792 Sure! You can open an issue here: https://github.com/ronanboiteau/NormEZ/issues

**Comment by valentinbreiz** [comment]
Thanks for your work!

**Pull request merged**
